name: Run Cypress Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs to the main branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the version of Node.js (adjust if needed)

      - name: Install dependencies
        run: |
          npm install  # Install project dependencies
          npm install cypress --save-dev  # Install Cypress if not already in package.json

      - name: Run Cypress tests
        run: npx cypress run --headless --browser chrome  # Run the tests headlessly in Chrome